services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Hot reload pour le dev
      - api-logs:/app/logs # Logs persistants
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistance BDD
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:v2.52.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  postgres-data: # Volume nommé géré par Docker
  api-logs: # Deuxième volume pour les logs
